import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



const handleAboveBelowSubmit = async (event: any) => {
    event.preventDefault()
    let csv: string[] = event.target.numbers.value.replaceAll(' ', '').split(',');

    let numbers = csv.map(num => parseInt(num))

    const data = {
        numbers: numbers,
        comparator: parseInt(event.target.comparator.value),
    }

    const JSONdata = JSON.stringify(data)

    const endpoint = '/api/aboveBelow'

    const options = {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSONdata,
    }

    const response = await fetch(endpoint, options)

    const result = await response.json()

    const resultElem = document.getElementById('result')!;

    resultElem.innerHTML = 'Above: ' + Math.max(0, result.above) + ' Below: ' + Math.max(0, result.below);

};


const handleStringRotationSubmit = async (event: any) => {
    event.preventDefault();

    const data = {
        stringToRot: event.target.stringToRot.value,
        rotateAmount: event.target.rotateAmount.value,
    }

    const JSONdata = JSON.stringify(data)

    const endpoint = '/api/stringRotation'

    const options = {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSONdata,
    }

    const response = await fetch(endpoint, options)

    const result = await response.json()

    const resultElem = document.getElementById('result')!;

    resultElem.innerHTML = 'Result : ' + result.stringRes

};


export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Some Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    I used this as an excuse to learn <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={styles.description} id="result">
                    I have only used Express before, this is neat!
                </p>

                <div className={styles.grid}>
                    <div className={styles.card}>
                        <h2>aboveBelow</h2>
                        <p>Input a list and comparator!</p><br></br>
                        <form onSubmit={handleAboveBelowSubmit}>
                            <label htmlFor="numbers">Comma Separated List</label>
                            <input type="text" id="numbers" name="numbers" pattern="[0-9]\s*+(,[0-9]+)*" required/><br></br>
                            <label htmlFor="comparator">Comparator</label>
                            <input type="number" id="comparator" name="comparator" pattern="[0-9]" required/><br></br><br></br>
                            <button type="submit">Submit</button>
                        </form>
                    </div>

                    <div className={styles.card}>
                        <h2>stringRotation &rarr;</h2>
                        <p>Input a list and comparator!</p><br></br>
                        <form onSubmit={handleStringRotationSubmit}>
                            <label htmlFor="stringToRot">String To Rotate</label>
                            <input type="text" id="stringToRot" name="stringToRot" required/><br></br>
                            <label htmlFor="rotateAmount">Rotate Amount</label>
                            <input type="text" id="rotateAmount" name="rotateAmount" pattern="^[1-9]\d*$" required/><br></br><br></br>
                            <button type="submit">Submit</button>
                        </form>
                    </div>

                </div>
            </main>

            <footer className={styles.footer}>
          

                A tiny project for RTS Labs
            </footer>
        </div>
    )
}


